### ISSUE TITLE
Comments on functional and design specifications

### ISSUE THREAD

**Issue by joseph-hellerstein** [TommyGPrimo/CRISPRaiCircuitsModeling#1]
Your functional spec has a nice narrative. However, you should have more detail about the interaction between the user and your tool. What does the tool display when started? What does the user enter and where? What does the tool display after the user's entries.

The component specification should be refined so that you can be more clear about what you need to build. Currently, you have only one component. Maybe, you'll only write one module. If that's the case, list components at the level of functions.

**Comment by TommyGPrimo** [comment]
Updated the functional and component specification, let me know if its clearer
